spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  h2:
    console.enabled: true
  kafka:
    bootstrap-servers: localhost:9092
    input-topic:
      name: input-topic
      partitions: 3
      replication-factor: 2
    output-topic:
      name: output-topic
      partitions: 3
      replication-factor: 2
